# Generated by Django 5.2.6 on 2025-09-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The publisher's name",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="The publisher's website URL",
                        null=True,
                        verbose_name="website",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The publisher's contact email",
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this publisher was added",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this publisher was last updated",
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the book",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        help_text="International Standard Book Number (unique)",
                        max_length=20,
                        unique=True,
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when this book was published",
                        null=True,
                        verbose_name="publication date",
                    ),
                ),
                (
                    "copies_total",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Total number of copies available in the library",
                        verbose_name="total copies",
                    ),
                ),
                (
                    "copies_available",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of copies currently available for checkout",
                        verbose_name="available copies",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this book was added",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this book was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        help_text="The authors of this book",
                        related_name="books",
                        to="books.author",
                        verbose_name="authors",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The category this book belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="books.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        help_text="The publisher of this book",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="books.publisher",
                        verbose_name="publisher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title", "publication_date"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(fields=["isbn"], name="books_book_isbn_54becd_idx"),
                    models.Index(
                        fields=["publication_date"],
                        name="books_book_publica_4f381a_idx",
                    ),
                ],
            },
        ),
    ]
