# Generated by Django 5.2.6 on 2025-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_publisher_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image of the book",
                null=True,
                upload_to="book_covers/",
                verbose_name="cover image",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="Language the book is written in",
                max_length=50,
                null=True,
                verbose_name="language",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="shelf_location",
            field=models.CharField(
                blank=True,
                help_text="Physical location of the book in the library",
                max_length=50,
                null=True,
                verbose_name="shelf location",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="A brief summary or description of the book",
                null=True,
                verbose_name="summary",
            ),
        ),
    ]
