# Generated by Django 5.2.6 on 2025-09-28 22:38

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for the parameter",
                        max_length=100,
                        verbose_name="Parameter Name",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-friendly label for the parameter",
                        max_length=100,
                        verbose_name="Display Label",
                    ),
                ),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("choice", "Choice"),
                        ],
                        max_length=20,
                        verbose_name="Parameter Type",
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="Default value for the parameter",
                        null=True,
                        verbose_name="Default Value",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this parameter is required",
                        verbose_name="Is Required",
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of choices for CHOICE type parameters",
                        null=True,
                        verbose_name="Choices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Parameter",
                "verbose_name_plural": "Report Parameters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the template",
                        max_length=100,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Template description and usage notes",
                        verbose_name="Description",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                        ],
                        default="html",
                        max_length=10,
                        verbose_name="Output Format",
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload template file if needed",
                        null=True,
                        upload_to="report_templates/",
                        verbose_name="Template File",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is active for use",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("overdue", "Overdue Books"),
                            ("borrowed", "Borrowed Books"),
                            ("fines", "Fines Report"),
                            ("popular_books", "Popular Books"),
                            ("active_users", "Active Users"),
                        ],
                        help_text="Type of the generated report",
                        max_length=50,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Structured data for the report",
                        verbose_name="Report Data",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the report was generated",
                        verbose_name="Generated At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this report is currently active or archived",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "scheduled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this report was generated by a scheduled task",
                        verbose_name="Scheduled Report",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Filters used to generate this report",
                        null=True,
                        verbose_name="Report Filters",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the report",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who generated this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_snapshot",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Snapshot of the report data at the time of archiving",
                        verbose_name="Report Data Snapshot",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this archive was created",
                        verbose_name="Archived At",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this archive",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived By",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="The report this archive belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="reports_app.report",
                        verbose_name="Original Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Archive",
                "verbose_name_plural": "Report Archives",
                "ordering": ["-archived_at"],
                "get_latest_by": "archived_at",
            },
        ),
        migrations.CreateModel(
            name="ReportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category",
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class (e.g., fa-chart-bar)",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="reports_app.reportcategory",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Category",
                "verbose_name_plural": "Report Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Enter your comment here", verbose_name="Comment"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this comment will only be visible to staff members",
                        verbose_name="Internal Note",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reports_app.reportcomment",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reports_app.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Comment",
                "verbose_name_plural": "Report Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                        verbose_name="Export Format",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="report_exports/%Y/%m/%d",
                        verbose_name="Exported File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Download Count"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this export will be automatically deleted",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="reports_app.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Export",
                "verbose_name_plural": "Report Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about this favorite",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="reports_app.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Report",
                "verbose_name_plural": "Favorite Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this recipient entry",
                        max_length=100,
                        verbose_name="Recipient Name",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("user", "System User"),
                            ("group", "User Group"),
                        ],
                        max_length=20,
                        verbose_name="Recipient Type",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Required for email recipients",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this recipient should receive reports",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Recipient",
                "verbose_name_plural": "Report Recipients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this schedule",
                        max_length=100,
                        verbose_name="Schedule Name",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("overdue", "Overdue Books"),
                            ("borrowed", "Borrowed Books"),
                            ("fines", "Fines Report"),
                            ("popular_books", "Popular Books"),
                            ("active_users", "Active Users"),
                        ],
                        max_length=50,
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Required for weekly frequency",
                        null=True,
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Required for monthly/quarterly frequency (1-31)",
                        null=True,
                        verbose_name="Day of Month",
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default="09:00",
                        help_text="When to generate the report",
                        verbose_name="Time of Day",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this schedule was last executed",
                        null=True,
                        verbose_name="Last Run",
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this schedule will run next",
                        null=True,
                        verbose_name="Next Run",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="Notification Frequency",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "last_notified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Notified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="reports_app.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Subscription",
                "verbose_name_plural": "Report Subscriptions",
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type"], name="reports_app_report__076319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_at"], name="reports_app_generat_1ca597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_by"], name="reports_app_generat_118851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["is_active"], name="reports_app_is_acti_1f18af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["scheduled"], name="reports_app_schedul_122727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportarchive",
            index=models.Index(
                fields=["report"], name="reports_app_report__79d528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportarchive",
            index=models.Index(
                fields=["archived_at"], name="reports_app_archive_c00ab2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportfavorite",
            unique_together={("user", "report")},
        ),
        migrations.AlterUniqueTogether(
            name="reportsubscription",
            unique_together={("user", "report")},
        ),
    ]
