# Generated by Django 5.2.6 on 2025-09-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("librarian", "Librarian"),
                    ("staff", "Staff"),
                    ("student", "Student"),
                ],
                default="student",
                help_text="Designates the type of user",
                max_length=10,
                verbose_name="user type",
            ),
        ),
    ]
