# Generated by Django 5.2.6 on 2025-09-28 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0005_book_cover_image_book_language_book_shelf_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when the book was borrowed",
                        verbose_name="borrow date",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Date when the book is due to be returned",
                        verbose_name="due date",
                    ),
                ),
                (
                    "return_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the book was actually returned",
                        null=True,
                        verbose_name="return date",
                    ),
                ),
                (
                    "is_returned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the book has been returned",
                        verbose_name="is returned",
                    ),
                ),
                (
                    "fine",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Fine amount for late return",
                        max_digits=6,
                        verbose_name="fine amount",
                    ),
                ),
                (
                    "renew_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the loan has been renewed",
                        verbose_name="renewal count",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the transaction",
                        null=True,
                        verbose_name="notes",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to="books.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "borrow transaction",
                "verbose_name_plural": "borrow transactions",
                "ordering": ["-borrow_date"],
            },
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fine amount in the local currency",
                        max_digits=6,
                        verbose_name="amount",
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the fine has been paid",
                        verbose_name="paid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this fine was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the fine was paid",
                        null=True,
                        verbose_name="paid at",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="The borrowing transaction this fine is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fine_record",
                        to="transactions.borrowtransaction",
                        verbose_name="borrow transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "fine",
                "verbose_name_plural": "fines",
            },
        ),
        migrations.AddConstraint(
            model_name="borrowtransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("return_date__isnull", True)),
                fields=("book", "user", "return_date"),
                name="unique_active_borrowing",
            ),
        ),
    ]
