# Generated by Django 5.2.6 on 2025-09-28 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0005_book_cover_image_book_language_book_shelf_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short title for this batch of notifications",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The content of the notifications",
                        verbose_name="message",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due", "Due Date Reminder"),
                            ("fine", "Fine Issued"),
                            ("new_arrival", "New Arrival"),
                            ("event", "Library Event"),
                            ("reservation", "Reservation"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        help_text="Type of the notification",
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional date when these notifications should expire",
                        null=True,
                        verbose_name="expiry date",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to direct users to a relevant page",
                        max_length=500,
                        null=True,
                        verbose_name="link",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this batch was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notifications have been sent to all users",
                        verbose_name="is sent",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notifications were sent to all users",
                        null=True,
                        verbose_name="sent at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this batch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notification_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        help_text="Users who will receive this notification",
                        related_name="notification_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="target users",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification batch",
                "verbose_name_plural": "notification batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("due", "Due Date Reminder"),
                            ("fine", "Fine Issued"),
                            ("new_arrival", "New Arrival"),
                            ("event", "Library Event"),
                            ("reservation", "Reservation"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        help_text="Type of the notification",
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The content of the notification",
                        verbose_name="message",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read by the user",
                        verbose_name="is read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the notification was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional date when this notification should expire",
                        null=True,
                        verbose_name="expiry date",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to direct the user to a relevant page",
                        max_length=500,
                        null=True,
                        verbose_name="link",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional book related to this notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="books.book",
                        verbose_name="book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who will receive this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "notification_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The batch this notification belongs to, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationbatch",
                        verbose_name="notification batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationbatch",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_0fbe0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatch",
            index=models.Index(
                fields=["is_sent"], name="notificatio_is_sent_0fd1ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="notificatio_user_id_8a7c6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["expiry_date"], name="notificatio_expiry__c79bc8_idx"
            ),
        ),
    ]
